// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAHwqUiOIGc4Gw05uKPLNV-68xuIKE3sCY',
    appId: '1:96719957610:web:6b07385810f3009e252413',
    messagingSenderId: '96719957610',
    projectId: 'borrachada-tickets',
    authDomain: 'borrachada-tickets.firebaseapp.com',
    storageBucket: 'borrachada-tickets.appspot.com',
    measurementId: 'G-38K8DP5QBD',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBuG06BgPzheqg6KcKIz9RGDtp-zOkpNxI',
    appId: '1:96719957610:android:5b287201b6bba252252413',
    messagingSenderId: '96719957610',
    projectId: 'borrachada-tickets',
    storageBucket: 'borrachada-tickets.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDGwq9y6w3YNxCja4W6Ja1vbeOfSbe4tBo',
    appId: '1:96719957610:ios:d14f6fa353c19004252413',
    messagingSenderId: '96719957610',
    projectId: 'borrachada-tickets',
    storageBucket: 'borrachada-tickets.appspot.com',
    iosClientId: '96719957610-ddfb3f6bdnqjiadnlhfub7lbhslp0ds6.apps.googleusercontent.com',
    iosBundleId: 'com.example.borrachada',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDGwq9y6w3YNxCja4W6Ja1vbeOfSbe4tBo',
    appId: '1:96719957610:ios:d14f6fa353c19004252413',
    messagingSenderId: '96719957610',
    projectId: 'borrachada-tickets',
    storageBucket: 'borrachada-tickets.appspot.com',
    iosClientId: '96719957610-ddfb3f6bdnqjiadnlhfub7lbhslp0ds6.apps.googleusercontent.com',
    iosBundleId: 'com.example.borrachada',
  );
}
